[tool.poetry]
name = "typytemplate"
version = "0.1.2"
description = "Lightweight Python project templating tool"
license = "Apache-2.0"
authors = ["StephanMalan <stephanmalan.rob@gmail.com>"]
readme = "README.md"
packages = [{ include = "typytemplate" }]


[tool.poetry.dependencies]
python = "^3.11"


[tool.poetry.scripts]
typytemplate = "typytemplate.main:main"


[tool.poetry.group.dev.dependencies]
black = "^23.7.0"
pylint = "^2.17.5"
mypy = "^1.5.1"
ruff = "^0.0.285"


[tool.poetry.group.test.dependencies]
pytest = "^7.4.0"
coverage = "^7.3.0"

[tool.black]
line-length = 120

[tool.ruff]
line-length = 120

[tool.pytest.ini_options]
pythonpath = ["."]

[tool.mypy]
strict = true
exclude = ["test", "alembic"]


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
