[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.poetry.dependencies]
python = ">=3.6"
beautifulsoup4 = ">=4.12.2"
requests = ">=2.31.0"


[project]
name = "Scraper_Ashutosh_kumar_Singh"
version = "1.0.3"
authors = [
  { name="Ashutosh Kumar Singh", email="ashutoshkumarsingh02032005@gmail.com" },
]
description = "A small package that makes web-scraping more Easier"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/E-techy/Web-Scraping-with-python"
