[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "ch5mpy"
description = "Collection of helper tools for reading or writing to h5 files using the h5py library."
version = "0.3.0"
requires-python = ">=3.7"
license = {file = "LICENSE"}
authors = [
    {name = "Matteo Bouvier", email = "m.bouvier@vidium-solutions.com"}
]
maintainers = [
    {name = "Matteo Bouvier", email = "m.bouvier@vidium-solutions.com"}
]
readme = {file = "README.md", content-type="text/markdown"}
dependencies = [
    "h5py",
    "numpy",
    "tqdm"
]
keywords = [
    "h5df",
    "h5py",
    "data storage",
    "data manipulation"
]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "License :: CeCILL-B Free Software License Agreement (CECILL-B)",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Topic :: File Formats",
    "Topic :: Scientific/Engineering",
    "Topic :: Scientific/Engineering :: Bio-Informatics",
    "Typing :: Typed"
]

[project.optional-dependencies]
docs = [
    "sphinx==6.1.3",
    "sphinx-autodoc-typehints==1.22",
    "sphinx-rtd-theme==1.2.0"
]

[project.urls]
Documentation = "https://ch5mpy.readthedocs.io/"
Source = "https://github.com/Vidium/ch5mpy"

[tool.setuptools.packages.find]
include = [
    "ch5mpy*",
    "ch5mpy.indexing"
]

[tool.setuptools.package-data]
"ch5mpy" = ["py.typed"]

[tool.vulture]
exclude = ["np.py"]
ignore_decorators = ["@implements"]
paths = ["ch5mpy", "vulture_whitelist.py"]

[tool.ruff]
line-length = 120
ignore = ["E701"]

[tool.mypy]
mypy_path = "stubs"

[[tool.mypy.overrides]]
module = ['h5py']
ignore_missing_imports = true
