[tool.poetry]
name = "fluxwallet"
version = "0.2.0"
description = "A Wallet implementation for Flux"
authors = ["David White <dr.white.nz@gmail.com>"]
license = "bsd 3-clause"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
# temp until move everything to httpx
requests = "^2.31.0"
httpx = "^0.24.1"
aiosqlite = "^0.19.0"
fastecdsa = { version = "^2.2.1", markers = "sys_platform != 'win32'" }
ecdsa = { version = "^0.17", platform = "win32" }
pycryptodome = "^3.14.1"
SQLAlchemy = "^2.0.19"
numpy = "^1.21.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"
