[tool.poetry]
name = "core-platano"
version = "0.3.0"
description = ""
authors = ["Ricardo Torrellas <ricardo.torrejas@gmail.com>"]
readme = "README.md"
packages = [
{include = "core_platano"},
{include = "core_platano/**/*.py"}
]

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
