[tool.poetry]
name = "alacorder"
version = "81.1.26"
description = "Alacorder retrieves case detail PDFs from Alacourt.com and processes them into data tables suitable for research purposes."
authors = ["Sam Robson <sbrobson@crimson.ua.edu>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
typer = {extras = ["all"], version = "^0.9.0"}
selenium = "^4.10.0"
polars = "^0.18.8"
pymupdf = "^1.22.5"
bs4 = "^0.0.1"
xlsxwriter = "^3.1.2"
xlsx2csv = "^0.8.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
