[tool.poetry]
name = "list-flatten"
version = "0.1.6"
description = "A simple python package to flatten a list of lists. Works for 2d and 3d lists."
authors = ["Sampurna Chapagain <sampurna.chapagainnn@gmail.com>"]
readme = "README.md"
license = "MIT"
repository = "https://github.com/SampurnaC/list-flatten"

[tool.poetry.dependencies]
python = "^3.8"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
