[tool.poetry]
name = "genesia"
version = "0.1.2"
description = "genesia cli"
authors = ["lucasmrdt <lucas.marandat@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
genesia-templates = "^0.1.5"
click = "^8.1.7"
yaspin = "^3.0.0"
python-socketio = {extras = ["client"], version = "^5.8.0"}
gitpython = "^3.1.32"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
genesia = "genesia_cli.cli:run_cli"