[tool.poetry]
name = "unpact"
version = "0.0.4"
description = "A lightweight library for tabulating dictionaries"
authors = ["Moph Toyer <chris@telemetry.fm>"]
license = "MIT"
readme = "README.md"
packages = [{include = "unpact"}]

[tool.poetry.dependencies]
python = "^3.9 || ^3.10 || ^3.11"

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.0"
black = "^23.7.0"
mypy = "^1.5.0"
poethepoet = "^0.22.0"
polars = "^0.18.14"
orjson = "^3.9.5"
msgspec = "^0.18.1"
ipykernel = "^6.25.1"

[tool.poe.tasks]
lint = "mypy unpact"
format = "black ."
check = "black . --check"
test = "pytest"
precommit = ["format", "lint", "test"]

[tool.black]
line-length = 120

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
