[tool.poetry]
name = "fysh"
version = "0.0.1.9"
description = "Command Line Interface tool for flockfysh."
authors = ["Ansh <teamnebulaco@gmail.com>"]
readme = "README.md"
repository = "https://github.com/flockfysh/ffysh"
license = "MIT"
keywords = ["files", "manipulation", "data science", ]
packages = [
    { include = "ffysh",  from = "src" },
]
classifiers =[
            "Programming Language :: Python :: 3",
            "Operating System :: OS Independent",
            "License :: OSI Approved :: MIT License",
]


[tool.poetry.dependencies]
python = ">=3.8, <4.0"
aiofiles = "^23.2.1"
aiohttp = "^3.8.5"
aiosignal = "^1.3.1"
async-timeout = "^4.0.3"
attrs = "^23.1.0"
build = "^0.10.0"
cachecontrol = "^0.13.1"
certifi = "^2023.7.22"
cffi = "^1.15.1"
charset-normalizer = "^3.2.0"
click = "^8.1.7"
cmake = "^3.27.2"
crashtest = "^0.4.1"
cryptography = "^41.0.3"
distlib = "^0.3.7"
docopt = "^0.6.2"
dulwich = "^0.21.5"
exceptiongroup = "^1.1.3"
filelock = "^3.12.2"
frozenlist = "^1.4.0"
gitdb = "^4.0.10"
html5lib = "^1.1"
idna = "^3.4"
importlib-metadata = "^6.8.0"
importlib-resources = "^6.0.1"
iniconfig = "^2.0.0"
installer = "^0.7.0"
jaraco-classes = "^3.3.0"
jeepney = "^0.8.0"
jinja2 = "^3.1.2"
jsonschema = "^4.19.0"
jsonschema-specifications = "^2023.7.1"
keyring = "^24.2.0"
lit = "^16.0.6"
lockfile = "^0.12.2"
markupsafe = "^2.1.3"
more-itertools = "^10.1.0"
mpmath = "^1.3.0"
msgpack = "^1.0.5"
multidict = "^6.0.4"
networkx = "^3.1"
ordered-set = "^4.1.0"
packaging = "^23.1"
pexpect = "^4.8.0"
pip = "^23.2.1"
pipreqs = "^0.4.13"
pkginfo = "^1.9.6"
pkgutil-resolve-name = "^1.3.10"
platformdirs = "^3.10.0"
pluggy = "^1.2.0"
psutil = "^5.9.5"
ptyprocess = "^0.7.0"
pycparser = "^2.21"
pyproject-hooks = "^1.0.0"
pytest = "^7.4.0"
python-dateutil = "^2.8.2"
pytz = "^2023.3"
rapidfuzz = "^3.2.0"
referencing = "^0.30.2"
refyre = "^0.0.1.5.2"
requests = "^2.31.0"
requests-toolbelt = "^1.0.0"
rpds-py = "^0.9.2"
secretstorage = "^3.3.3"
setuptools = "^68.1.2"
shellingham = "^1.5.3"
six = "^1.16.0"
smmap = "^5.0.0"
sympy = "^1.12"
tomli = "^2.0.1"
tomlkit = "^0.12.1"
trove-classifiers = "^2023.8.7"
typing-extensions = "^4.7.1"
tzdata = "^2023.3"
urllib3 = "^2.0.4"
webencodings = "^0.5.1"
wheel = "^0.41.1"
yarg = "^0.1.9"
yarl = "^1.9.2"
zipp = "^3.16.2"


[tool.poetry.dev-dependencies]
pytest = {version="^7.0.1", python = ">=3.7,<4.0"}

[tool.poetry.scripts]
ffysh = "ffysh.cli:main"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.extras]
torch = ["torch", "torchvision", "numpy"]