[tool.poetry]
name = "reg-stat-inference"
version = "0.1.3"
description = "Treat multicollinearity and non-significant variables from your statsmodels linear and logistic regressions"
authors = ["Dirceu Silva <ddasilvajunior@vio.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.7"
statsmodels = "^0.12.0"
pandas = "^2"
numpy = "^1.20"


[tool.poetry.group.dev.dependencies]
black = "^23.7.0"
scikit-learn = "^1.3.0"
seaborn = "^0.12.2"


[tool.poetry.group.test.dependencies]
pytest = "^7.4.0"
requests-mock = "^1.11.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
